### ISSUE TITLE
How many edges does a mystery have?

### ISSUE THREAD

**Issue by Sebirlinem** [soldeviFae/The-man-next-door#13]
![screenshot_20160420-201251](https://cloud.githubusercontent.com/assets/10555632/14696215/8c6c1dc0-07bc-11e6-9d89-f2c85fbc4e59.png)

Robin Creed's post on day 0: "Nothing like some old good friends and some dear drinks to take the edge **of** a mystery"

**Comment by calliePepper** [comment]
Fixed in b8d8c190afe52e8ddb4a754d988b2340def9b8b2
