### ISSUE TITLE
Odd message combo for Robin's day 0 chat

### ISSUE THREAD

**Issue by Sebirlinem** [soldeviFae/The-man-next-door#14]
![screenshot_20160420-191015](https://cloud.githubusercontent.com/assets/10555632/14696252/c26126e6-07bc-11e6-866f-703283ea93b9.png)

In the initial conversation with Robin creed on day 0 I ended up with this odd combination:
- **Robin:** I'll let you know if I need anything more.
- **Robin:** Ill give you something to start on though
- **Me:** What is it?
- **Robin:** That's a nice offer, but I think I'll stick to the research front
- **Robin:** You can't really research what you can't see, but if I find some material for you to look at, you can help with that.
- **Robin:** But here's what I was talking about

**Comment by calliePepper** [comment]
Fixed in b8d8c190afe52e8ddb4a754d988b2340def9b8b2
