### ISSUE TITLE
Unexpected image layering in Messaging conversation

### ISSUE THREAD

**Issue by Sebirlinem** [soldeviFae/The-man-next-door#15]
![screenshot_20160420-191142](https://cloud.githubusercontent.com/assets/10555632/14696338/7ad506de-07bd-11e6-890c-58e36e1a4e03.png)

In the initial conversation with Robin Creed on day 0, when he shares the image of the symbol he recognised painted on the house. As the conversation continues and the image moves up, it is layered above the bar with "< Robin Creed" instead of under like the rest of the conversation panel text.

**Comment by calliePepper** [comment]
Fixed in b8d8c190afe52e8ddb4a754d988b2340def9b8b2
